### ISSUE TITLE
Errors loading files

### ISSUE THREAD

**Issue by arminta7** [M7mdisk/obsidian-gpt#1] opened 2023-03-11 14:54 UTC
<img width="683" alt="Screenshot 2023-03-11 at 09 54 02" src="https://user-images.githubusercontent.com/7927356/224491400-d923b7ec-b002-49d7-978b-930f60d8aa0f.png">

**Comment by M7mdisk** [comment] 2023-03-11 17:23
This looks like a network issue, my suspicion is that the data is too large for the request as I havent tested this on large vaults.

could you please check the request sent through the Network tab and how large the data sent is? 
The detailed request/response headers and errors would be nice to have as well.

**Comment by arminta7** [comment] 2023-03-11 19:59
I'm testing on a small vault, < 500 notes. 

<img width="738" alt="Screenshot 2023-03-11 at 14 59 18" src="https://user-images.githubusercontent.com/7927356/224509108-a3875bab-921d-4ec0-a8d2-2be126ef964d.png">

**Comment by M7mdisk** [comment] 2023-03-12 10:12
Please provide a dump of the failed request by right clicking and clicking "Save all as HAR".

**Comment by source-toad** [comment] 2023-03-21 13:37
Was this able to be resolved? I am having the same issue - also a small vault.

**Comment by M7mdisk** [comment] 2023-03-21 16:25
I have not been able to reproduce this, vault size doesn't seem to be the issue as well.
What is the error exactly, could you try on a new vault and check if it still happens?
if so, please provide a dump of the failed request by right clicking it and clicking "Save all as HAR".

**Comment by M7mdisk** [comment] 2023-03-29 18:59
@vreoo this is a different issue, your OpenAI API quota expired. :)
I'll add some better error handeling on the UI but this isnt a problem with the plugin.

I'll close this issue for now since its still irreproducible.

**Closed by M7mdisk** 2023-03-29 18:59 UTC
